package model;

import com.google.gson.annotations.SerializedName;

public class Users {

    /**
     * A String containing the username for the User
     */
    @SerializedName("userName")
    private String userName;
    /**
     * A String containing the password associated with the User
     */
    @SerializedName("password")
    private String password;
    /**
     * A String containing the email address for the User
     */
    @SerializedName("email")
    private String email;
    /**
     * A String containing the User's first name
     */
    @SerializedName("firstName")
    private String firstName;
    /**
     * A String containing the User's last name
     */
    @SerializedName("lastName")
    private String lastName;
    /**
     * A String containing an initial representing the User's gender (must be "m" or "f" only)
     */
    @SerializedName("gender")
    private String gender;
    /**
     * A String containing a personID that is associated with this User generated by the server
     */
    @SerializedName("personID")
    private String personID;

    /**
     * Constructor for the Users class. Sets username, password, email, firstName, lastName
     * gender, and personID fields
     *
     * @param username The User's selected username.
     * @param password The User's selected password.
     * @param email The User's given email address.
     * @param firstName The User's given first name.
     * @param lastName The User's given last name.
     * @param gender The User's specified gender.
     * @param personID The User's associated personID from the server.
     */
    public Users(String username, String password,
          String email, String firstName,
          String lastName, String gender, String personID) {
        this.userName = username;
        this.password = password;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.personID=personID;
    }

    public String getUsername() {
        return userName;
    }

    public void setUsername(String username) {
        this.userName = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getPersonID() {
        return personID;
    }

    public void setPersonID(String personID) {
        this.personID = personID;
    }

    /**
     * An Override version of the equals function for the Users class.
     * Checks each individual data member with another Object o.
     *
     * @param o Object to be compared. If o is of type user, then it is wrapped for comparison using getter/setter functions.
     * @return Returns false if any non-matches are found, otherwise true if all data members match.
     */
    @Override
    public boolean equals(Object o) {
        if (o == null) {
            return false;
        }
        if (o instanceof Users) {
            Users oUser = (Users) o;
            return oUser.getUsername().equals(getUsername()) &&
                    oUser.getPassword().equals(getPassword()) &&
                    oUser.getEmail().equals(getEmail()) &&
                    oUser.getFirstName().equals(getFirstName()) &&
                    oUser.getLastName().equals(getLastName()) &&
                    oUser.getGender().equals(getGender()) &&
                    oUser.getPersonID().equals(getPersonID());
        }
        else {
            return false;
        }
    }
}